blank_issues_enabled: true
contact_links:
  - name: Report Issues in Case Conversion
    url: https://github.com/ryonakano/chcase/issues/new
    about: For reporting a problem in the case conversion or ask for additional conversion option (e.g. an unexpected conversion result, support converting to/from another case, etc.)
  - name: Report Issues in App Itself
    url: https://github.com/ryonakano/konbucase/issues/new
    about: For reporting a problem in the UI or new features of the app itself (e.g. broken UI, add another button to do something, etc.)
