blank_issues_enabled: false
contact_links:
  - name: Report issues in the case conversion
    url: https://github.com/ryonakano/chcase/issues/new
    about: Choose this when you are reporting a problem related to the case conversion e.g. an unexpected conversion output, or ask for additional conversion option e.g. support converting to/from another case.
